### PR TITLE
Added USDe support

### PR DESCRIPTION
**Pull request by 0xprinc**
Integrated Fluid USDe vaults.
We have tested locally and it works fine.

### CODE REVIEW

**Comment by 0xprinc** [comment]
Hey @FJ-Riveros 
This PR is ready for review. It would be amazing if you could take a look!!

**Comment by FJ-Riveros** [comment]
> Hey @FJ-Riveros This PR is ready for review. It would be amazing if you could take a look!!

Hey @0xprinc! Sorry for the delay, will take a look today, thanks!

**Comment by FJ-Riveros** [comment]
@0xprinc Looks good so far. Just to confirm, the USDe vaults aren't deployed yet, right? 
Since the `get_balance` and `get_participants` methods return nothing yet and can't find them in your UI

**Comment by FJ-Riveros** [comment]
> @FJ-Riveros We have USDe vaults but not any active positions. The tests were running on old block numbers, when we had no USDe vaults. I have now changed the tests to fetch and include latest block numbers.

@0xprinc Looks good, thanks! Approving & merging

**Pull request merged**
