### PR TITLE
Add beefy integration

### PR DESCRIPTION
**Pull request by prevostc**

### CODE REVIEW

**Comment by FJ-Riveros** [comment]
@prevostc Hey! 
We are looking into integrating beefy, the only issue that we see is that your API returns this error when trying to get the Arbitrum users when using this endpoint: `https://lrt.beefy.finance/api/v2/partner/ethena/arbitrum/users`

`{"error":"FriendlyError: Unknown platformId convex for vault curve-arb-usde-usdx. Devs need to implement breakdown for this protocol"}`

**Comment by prevostc** [comment]
Hi @FJ-Riveros thx for merging the PR, just fixed the API, please let me know if that works for you

**Comment by FJ-Riveros** [comment]
> https://lrt.beefy.finance/api/v2/partner/ethena/arbitrum/users

@prevostc Yep that works! Thanks!

**Comment by deHB6** [comment]
@prevostc we are seeing an issue where one user who seems to have a balance according to debank, your api is returning 0 on arbitrum

could we discuss on telegram? https://t.me/+PCfeDL8S_08zZjRh

The transaction hash they shared indicates they entered the LP three days ago: 0x88400C8D91681F9d1B263eB8479cf4F391938e1F. 19k USDe USDC LP position
telegram-cloud-document-4-5958594733184915504

**Comment by prevostc** [comment]
@deHB6  should be fixed now, can you check?

**Pull request merged**
